builtins: rand.intn (#74)
* builtins: rand.intn

Resolves #38

Signed-off-by: Dmitry Frenkel <d_frenkel@apple.com>

* Registry: lint fix

Was:

  $ swift format lint --strict --parallel --recursive .
  Sources/Rego/Builtins/Registry.swift:188:5: error: [UseSynthesizedInitializer]
  remove this explicit initializer, which is identical to the compiler-synthesized
  initializer

Signed-off-by: Stephan Renatus <s_renatus@apple.com>

---------

Signed-off-by: Dmitry Frenkel <d_frenkel@apple.com>
Signed-off-by: Stephan Renatus <s_renatus@apple.com>
Co-authored-by: Dmitry Frenkel <d_frenkel@apple.com>