Registry: lint fix
Was:

  $ swift format lint --strict --parallel --recursive .
  Sources/Rego/Builtins/Registry.swift:188:5: error: [UseSynthesizedInitializer]
  remove this explicit initializer, which is identical to the compiler-synthesized
  initializer

Signed-off-by: Stephan Renatus <s_renatus@apple.com>